### ISSUE TITLE
Consider using gazebo_ros::Node instead of rclcpp:Node

### ISSUE THREAD

**Issue by chapulina** [ros-simulation/gazebo_ros2_control#10]
I just realized `rclcpp::Node` is being used:

https://github.com/ros-simulation/gazebo_ros2_control/blob/98834ef700c1c6ffd3012d2de0a81a09ab2d2235/gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp#L64-L65

But if you used [gazero_ros::Node](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/ros2/gazebo_ros/include/gazebo_ros/node.hpp), you'd get the advantages listed [here](http://gazebosim.org/tutorials?tut=ros2_overview&cat=connect_ros) and [here](https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-integration#migration-notes-3), so you don't need to worry about executors or parsing common SDF params.

**Comment by ahcorde** [comment]
PR https://github.com/ros-simulation/gazebo_ros2_control/pull/11
