### ISSUE TITLE
Add a diff_driver demo

### ISSUE THREAD

**Issue by 0smile** [ros-simulation/gazebo_ros2_control#104]
Hi, can we add a diff_driver demo for gazebo_ros2_control, like they do in ros2_control repository? It will help a lot for beginners on ros2_control and gazebo_ros2_control like me! @v-lopez seems to achieve it in https://github.com/ros-simulation/gazebo_ros2_control/pull/44#issuecomment-772064321, thanks a lot if you can share your code in some ways!

**Comment by bmagyar** [comment]
We have a separate repository for demos at https://github.com/ros-controls/ros2_control_demos
Perhaps you'll find what you are looking for there already and if not, please open an issue there and we can work together on a good example.
