### ISSUE TITLE
ROS2 Foxy mimic joint control

### ISSUE THREAD

**Issue by beta1scat** [ros-simulation/gazebo_ros2_control#112]
How to use ROS2 Foxy + MoveIt2 + Gazebo to realized a mimic joint control?
I only see the master branch has a demo of mimic joint control for the parallel gripper. But I can't build the master branch on ROS2 Foxy.

**Comment by bmagyar** [comment]
The master branch is never to be expected to work on distributions other than ROS2 Rolling.
We try our best to backport features to ROS2 Foxy but this one is incompatible.

**Comment by ahcorde** [comment]
Thank you for the answer @bmagyar !  Closing the issue.

**Comment by beta1scat** [comment]
Thank you all!

**Comment by leander-dsouza** [comment]
@beta1scat 
Please let me know if #121 works.
