### ISSUE TITLE
gazebo_system.cpp:205:29: error: ‘const struct hardware_interface::InterfaceInfo’ has no member named ‘initial_value’

### ISSUE THREAD

**Issue by AmetistDrake** [ros-simulation/gazebo_ros2_control#115]
I am trying to build the packages with colcon locally after rosdep install, but the build fails with the following error:
`gazebo_system.cpp:205:29: error: ‘const struct hardware_interface::InterfaceInfo’ has no member named ‘initial_value’`

**Comment by ahcorde** [comment]
`initial_value` is only available in Rolling (Humble). Which ROS distro are you using ?

**Comment by AmetistDrake** [comment]
@ahcorde I am using galactic

**Comment by ahcorde** [comment]
Please use the `galactic` gazebo_ros2_control branch
