### ISSUE TITLE
Remove legacyModeNS?

### ISSUE THREAD

**Issue by chapulina** [ros-simulation/gazebo_ros2_control#14]
I saw that the `legacyModeNS` option has been migrated from ROS 1 to this package:

https://github.com/ros-simulation/gazebo_ros2_control/blob/a1318f8b1da9285ea3f647f575c1b37c1ef2975d/gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp#L179-L194

Given that option's name, I'd expect it to be the kind of thing that doesn't need to be perpetuated into ROS 2. Is that still necessary?

**Comment by ahcorde** [comment]
https://github.com/ros-simulation/gazebo_ros2_control/pull/17
