### ISSUE TITLE
Only support Gazebo 9+

### ISSUE THREAD

**Issue by chapulina** [ros-simulation/gazebo_ros2_control#15]
This package builds on top of `gazebo_ros_pkgs`, and that package's ROS 2 integration has been explicitly targeting only Gazebo versions above 9. On the [contribution guide](https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-contribution-guide#in-the-code-1) we recommend "_Remove all ifdefs for GAZEBO_MAJOR_VERSION for Gazebo 8 and below._"

So I recommend doing the same on this package, on parts like this:

https://github.com/ros-simulation/gazebo_ros2_control/blob/a1318f8b1da9285ea3f647f575c1b37c1ef2975d/gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp#L206-L211

**Comment by ahcorde** [comment]
https://github.com/ros-simulation/gazebo_ros2_control/pull/18
