### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by chapulina** [ros-simulation/gazebo_ros2_control#16]
I think there aren't tests yet, but it would be good to run some basic CI to make sure this package can be compiled and linters are clean.

The CI can also work as documentation on how to setup an environment, because there's a lot being pulled from various places right now.

**Comment by ahcorde** [comment]
https://github.com/ros-simulation/gazebo_ros2_control/pull/19

**Comment by ahcorde** [comment]
PR is merged
