### ISSUE TITLE
Consider switching to snake_case inside XML

### ISSUE THREAD

**Issue by chapulina** [ros-simulation/gazebo_ros2_control#22]
As described on #12 , the SDF parameters being passed to this plugin currently use `camelCase`, i.e.:

```
    <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
      <robotSimType>gazebo_ros2_control/DefaultRobotHWSim</robotSimType>
      <robotParamNode>robot_state_publisher</robotParamNode>
      <parameters>$(find gazebo_ros2_control_demos)/config/cartpole_controller.yaml</parameters>
    </plugin>
```

Because both SDF and URDF use `snake_case` in their specs, when porting `gazebo_ros_pkgs` to ROS 2, we also changed its XML elements to use that style, see [this example](https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-Migration:-Diff-drive#sdf-parameters).

I recommend using the same here, but feel free to close this issue if you think it's not worth it.

**Comment by ahcorde** [comment]
PR https://github.com/ros-simulation/gazebo_ros2_control/pull/24
