### ISSUE TITLE
Use rosdep to install dependencies in CI

### ISSUE THREAD

**Issue by chapulina** [ros-simulation/gazebo_ros2_control#26]
Right now several dependencies are being explicitly installed in CI:

https://github.com/ros-simulation/gazebo_ros2_control/blob/6b3028db81291666c7d615d3c51351ecb92c559a/.github/workflows/ci.yaml#L25-L31

It should be possible to use `rosdep` to install all dependencies as listed on `package.xml`, this way when new dependencies are added CI doesn't need to be updated.

For example:

```
rosdep install --from-paths ./ -i -y --rosdistro foxy \
  --skip-keys=ros2_control \
  ...
```

This is just a suggestion, feel free to ignore.

**Comment by ahcorde** [comment]
PR https://github.com/ros-simulation/gazebo_ros2_control/pull/27
