### ISSUE TITLE
 Can't build on Foxy distro

### ISSUE THREAD

**Issue by kong2983** [ros-simulation/gazebo_ros2_control#39]
I tried to build this package. However, it is impossible to build because the package compatibility is not appropriate. If you try to build by cloning the latest version of the ros2_control package, you cannot build it because there is no joint_state_handle package. 
Is there any way to solve this problem?

**Comment by ahcorde** [comment]
Hi @kong2983,

Some new changes are happening right now in `ros2_control`. 

For now you can compile the current `gazebo_ros2_control`, `ros2_control` and `ros2_controller` master branch with the branch of this PR https://github.com/ros-simulation/gazebo_ros2_control/pull/34#issuecomment-716975698 (`ahcorde/update/ros2_control`).

Let me know if you have some issue compiling this branch.

**Comment by kong2983** [comment]
I have confirmed that the example works normally.
Thank you for the reply!

**Comment by heike380** [comment]
Hi @kong2983, 

how did you build the "ahcorde/update/ros2_control"-branch? 
I built the "ahcorde/update/ros2_control" with docker (docker build -t gazebo_ros2_control .), but still got the error that "JointStateHandle" wasn't found. 

Thanks.

**Comment by kong2983** [comment]
@heike380 

The "ahcorde/update/ros2_control"-branch does not use JointStateHandle.
It seems that the master branch is installed while building with docker.
I didn't build with docker. Try again with the command below.

git clone -b ahcorde/update/ros2_control --single-branch https://github.com/ros-simulation/gazebo_ros2_control
git clone https://github.com/ros-controls/ros2_control
git clone https://github.com/ros-controls/ros2_controllers

**Comment by heike380** [comment]
@kong2983 

Thanks! Perfect, now it builds.

I just adapted "git clone https://github.com/ros-simulation/gazebo_ros2_control" to "git clone -b ahcorde/update/ros2_control --single-branch https://github.com/ros-simulation/gazebo_ros2_control" in the Dockerfile.
