### ISSUE TITLE
Wrong config value for velocity and effort yaml 

### ISSUE THREAD

**Issue by olivier-stasse** [ros-simulation/gazebo_ros2_control#50]
Dear @ahcorde  thanks for the great work !
I believed that https://github.com/ros-simulation/gazebo_ros2_control/blob/8bdfcf12c690a75ffc2a76ec931d8daae94c3157/gazebo_ros2_control_demos/config/cartpole_controller_effort.yaml#L15 should be
`effort` instead of `position`
The same goes for the velocity example.

**Comment by ahcorde** [comment]
@olivier-stasse yes, you are right, here it's the patch https://github.com/ros-simulation/gazebo_ros2_control/pull/51
