### ISSUE TITLE
State::interface not created.

### ISSUE THREAD

**Issue by olivier-stasse** [ros-simulation/gazebo_ros2_control#52]
Dear @ahcorde,

I believe that 
https://github.com/ros-simulation/gazebo_ros2_control/blob/79207cc7d7630a8aeced1b9f5bba985e0805e538/gazebo_ros2_control/src/gazebo_system.cpp#L171

should be

`this->dataPtr->joint_pos_state_[j] = std::make_shared<hardware_interface::StateInterface>(
          joint_name, hardware_interface::HW_IF_POSITION, &this->dataPtr->joint_position_[j]);`

The same goes for velocity and effort.

Do you agree or did I misunderstood ?

**Comment by ahcorde** [comment]
Nice catch!  https://github.com/ros-simulation/gazebo_ros2_control/pull/53
