### ISSUE TITLE
Unnecessary parameter in demo

### ISSUE THREAD

**Issue by JaehyunShim** [ros-simulation/gazebo_ros2_control#57]
As the title says, the below lines should be removed. (it does not cause any problem now since they are removed afterward by [this line]( https://github.com/ros-controls/ros2_controllers/blob/master/velocity_controllers/src/joint_group_velocity_controller.cpp#L44))

https://github.com/ros-simulation/gazebo_ros2_control/blob/master/gazebo_ros2_control_demos/config/cartpole_controller_effort.yaml#L15

https://github.com/ros-simulation/gazebo_ros2_control/blob/master/gazebo_ros2_control_demos/config/cartpole_controller_velocity.yaml#L15

**Comment by Karsten1987** [comment]
I had a similar comment for the ros2_control demos. might be a copy-paste error?
cc @destogl

**Comment by destogl** [comment]
Yes, this is definitely a copy-paste error. @JaehyunShim would you open a PR?

**Comment by ahcorde** [comment]
PR https://github.com/ros-simulation/gazebo_ros2_control/pull/68

**Comment by JaehyunShim** [comment]
@ahcorde  Thanks!
