### ISSUE TITLE
Colcon build error

### ISSUE THREAD

**Issue by padhupradheep** [ros-simulation/gazebo_ros2_control#61]
Hey Guys, 

I'm trying to build this package in ROS-Foxy on ubuntu 20.04 but the build is failing as follows: 

`--- stderr: gazebo_ros2_control                         
CMake Error at /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Could not find a configuration file for package "ignition-common3-graphics"
  that exactly matches requested version "3.10.0".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/ignition-common3-graphics/ignition-common3-graphics-config.cmake, version: 3.6.0
    /lib/x86_64-linux-gnu/cmake/ignition-common3-graphics/ignition-common3-graphics-config.cmake, version: 3.6.0

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/ignition-common3/ignition-common3-config.cmake:203 (find_dependency)
  /usr/lib/x86_64-linux-gnu/cmake/gazebo/gazebo-config.cmake:209 (find_package)
  /opt/ros/foxy/share/gazebo_dev/cmake/gazebo_dev-extras.cmake:2 (find_package)
  /opt/ros/foxy/share/gazebo_dev/cmake/gazebo_devConfig.cmake:41 (include)
  CMakeLists.txt:7 (find_package)

---
Failed   <<< gazebo_ros2_control [7.52s, exited with code 1]
`
Any help here will be great !

**Comment by Kakcalu13** [comment]
Did you find out how to solve this issue?
