### ISSUE TITLE
Loader for controller "effort_controllers" not found

### ISSUE THREAD

**Issue by lachwot** [ros-simulation/gazebo_ros2_control#62]
Hi,
Apologies if this is a simple fix or a known bug, (or if I've misread the docs :stuck_out_tongue: ), but I cant seem to run the `effort` demonstration that you have here in the repo (the ones via docker). I can run the `position` and `velocity` demos running fine but the `effort` one eventually terminates with the error `[controller_manager]: Loader for controller 'effort_controllers' not found`.

My understanding is that I run: 

`docker run -it --rm --name gazebo_ros2_control_demo --net host gazebo_ros2_control ros2 launch gazebo_ros2_control_demos cart_example_effort.launch.py gui:=false`

Where we have `gazebo_ros2_control_demos cart_example_effort.launch.py` rather than `gazebo_ros2_control_demos cart_example_position.launch.py`.

I am not sure where to look to fix it (it might be the `package.xml` file missing the right `exec_depends`?)
I hope to see this demo run since I plan on implementing torque/effort controllers on 4 individual revolute joints on a rover/car model that I have in Gazebo.

Thanks in advance for any insight you can provide! 

-Lachlan

**Comment by ahcorde** [comment]
This should fix the issue https://github.com/ros-simulation/gazebo_ros2_control/pull/69
