### ISSUE TITLE
rocker instruction does not work 

### ISSUE THREAD

**Issue by JaehyunShim** [ros-simulation/gazebo_ros2_control#63]
Hi, 

[This rocker instruction](https://github.com/ros-simulation/gazebo_ros2_control#using-rocker) does not work. The below line is the error message from the terminal. 

```sh
Failed to build detector image
WARNING unable to detect os for base image 'gazebo_ros2_control:latest', maybe the base image does not exist
```

Regards,
Jaehyun

**Comment by ahcorde** [comment]
Probably you have discovered the solution, but you should compile your own docker file

**Comment by JaehyunShim** [comment]
@ahcorde 

Yeah, that was the problem and thank you for your reply. I will reopen this thread if I have other relevant questions. 

Jaehyun

**Comment by alimhn** [comment]
i have the same problem:

no more output and success not detected
Failed to build detector image
WARNING unable to detect os for base image 'zenoh-carla-bridge', maybe the base image does not exist.
