### ISSUE TITLE
Difference bet. gazebo_ros_control and gazebo_ros2_control ?

### ISSUE THREAD

**Issue by newcanopies** [ros-simulation/gazebo_ros2_control#72]
Hi, 

Can anyone clarify the difference between:

`ros-simulation/gazebo_ros_pkgs/`**`gazebo_ros_control`** which has a ROS2 Foxy branch
https://github.com/ros-simulation/gazebo_ros_pkgs/tree/foxy/gazebo_ros_control

and this `repo ros-simulation/`**`gazebo_ros2_control`** ?

**Comment by ahcorde** [comment]
As you can see in this issue https://github.com/ros-simulation/gazebo_ros_pkgs/pull/1108 and this other discussion https://github.com/ros-simulation/gazebo_ros_pkgs/issues/179 is that `gazebo_ros_control` will be in its own repository for ROS 2.0.

this folder should be removed and by the way there is no code inside. Nothing to be worried about.
